name: GitHub Notifications to Discord

on:
  push:
  pull_request:
  issues:
  release:
  create:
  delete:
  pull_request_review:
  pull_request_review_comment:
  issue_comment:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send GitHub event to Discord
        uses: bbsw/discord-webhook@v1
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            ${{ toJSON(github.event) }}
