name: discord notify

on:
  push:
    branches: [ "**" ]

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: send push to discord
        uses: step-security/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            push: ${{ github.repository }}@${{ github.ref_name }}
            commit: ${{ github.sha }}
            author: ${{ github.actor }}
            message: ${{ github.event.head_commit.message }}